export const CONSTRUCTOR_ORDER = 'CONSTRUCTOR_ORDER';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ITEM_PROPERTIES = 'ADD_ITEM_PROPERTIES';
export const CONSTRUCTOR_ORDER_SORT = 'CONSTRUCTOR_ORDER_SORT';






